services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:8080"
    env_file:
      - ./backend/.env
    # environment:
    #   - MONGO_URI=mongodb://localhost:27017/react_express_ecommerce
    depends_on:
      - frontend
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:80"
    restart: always
